mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('news.urls')),
    path('admin/', admin.site.urls),
]

news/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views
from .rest_api import api_urls

urlpatterns = [
    path('', views.PostList.as_view(), name='index'),
    path('favicon.ico', RedirectView.as_view(url='/static/news/favicon.ico', permanent=True)),
    path('new-post', views.PostCreate.as_view(), name='new-post'),
    path('delete-post/<int:pk>', views.PostDelete.as_view(), name='delete-post'),
    path('post/<int:pk>', views.PostDetail.as_view(), name='post'),
] + api_urls

news/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=1000)
    text = models.TextField()
    date = models.DateTimeField()

news/views.py
from django.http import HttpResponse
from django.views import generic
from django.utils import timezone
from django.urls import reverse_lazy
from .models import Post


class PostList(generic.ListView):
    model = Post


class PostCreate(generic.CreateView):
    model = Post
    fields = ['title', 'text']
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        form.instance.date = timezone.now()
        return super().form_valid(form)


class PostDetail(generic.DetailView):
    model = Post
    fields = "__all__"


class PostDelete(generic.DeleteView):
    model = Post
    success_url = reverse_lazy("index")

news/templates/news/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	{% load static %}
    <link rel="icon" sizes="192x192" href="{% static "news/icon-touch.png" %}">
    <link rel="shortcut icon" href="{% static "news/favicon.ico" %}">

    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    <div class="container p-3">
        {% block content %}{% endblock content %}
    </div>
</body>

</html>

news/templates/news/post_confirm_delete.html
{% extends "news/base.html" %}
{% block title %} Confirm post deletion {% endblock %}
{% block content %}
<h1>Confirm deletion of post "{{ post.title }}"</h1>
<form method="post">{% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Confirm">
    <a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

news/templates/news/post_detail.html
{% extends "news/base.html" %}
{% block title %}Post: {{ post.title }}{% endblock %}
{% block content %}
<h1>{{ post.title }}</h1>
<p class="text-muted">Posted on {{ post.date }}</p>
<p>{{ post.text }}</p>
<a href="{% url 'index' %}" class="btn btn-secondary">Back</a>
<a href="{% url 'delete-post' post.pk %}" class="btn btn-outline-danger">Delete</a>
{% endblock %}

news/templates/news/post_form.html
{% extends "news/base.html" %}
{% block title %} New post {% endblock %}
{% block content %}
<h1>Create a new post</h1>
<form method="post">{% csrf_token %}
    <input class="form-control mb-3" name="title" id="id_title" type="text" placeholder="Title" required>
    <textarea class="form-control mb-3" name="text" id="id_text" rows="10" placeholder="Post text" required></textarea>
    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="{% url 'index' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

news/templates/news/post_list.html
{% extends "news/base.html" %}
{% block title %} Latest news {% endblock %}
{% block content %}
<h1>{{post_list.count}} available posts</h1>
<div class="list-group mb-3">
    {% for post in post_list %}
    <a href="{% url 'post' post.id %}" class="list-group-item list-group-item-action">{{ post.title }}</a>
    {% endfor %}
</div>
<a href="{% url 'new-post' %}" class="btn btn-primary">Create a new post</a>
{% endblock %}